export default {
    "Бэк": "https://dl.dropbox.com/s/rcq3qus5ujys28v/back.mp3",
    "Бегу сука за тобой": "https://dl.dropbox.com/s/rcq3qus5ujys28v/back.mp3",
    "Да да да": "https://dl.dropbox.com/s/wk2k0lmc0dmrebb/dada.mp3",
    "Даун": "https://dl.dropbox.com/s/pi0nw4s9d7i5a75/daun.wav.mp3",
    "Дякую": "https://dl.dropbox.com/s/t9e2nh93e0c7ryy/diakuju.mp3",
    "Але у вас долбоеб завис": "https://dl.dropbox.com/s/0ao3cg5loyw1ca3/dolboeb_zavis.mp3",
    "Факинг треш": "https://dl.dropbox.com/s/2zsd3ucvc4urypn/fucking_trash.mp3",
    "Горе побежденным": "https://dl.dropbox.com/s/bf7hxisiusl4692/gore.mp3",
    "Хелп": "https://dl.dropbox.com/s/dtstm4pxz4fsm6w/heeelp.wav.mp3",
    "Хелоу": "https://dl.dropbox.com/s/byddxsfc65lxcnr/hello.mp3",
    "Я иду додому": "https://dl.dropbox.com/s/1owtzwo6i44pvmm/idu.mp3",
    "Изи изи изи": "https://dl.dropbox.com/s/vpinkcm13jqe8ai/izi_izi_izi.mp3",
    "Как дела": "https://dl.dropbox.com/s/z5c44mw3qajvure/kak_dela.mp3",
    "Тебя схватил 120кг нехр": "https://dl.dropbox.com/s/66dn3xfhibjcr1e/kg.mp3",
    "Лс дцп уебок умри": "https://dl.dropbox.com/s/f3gvtlh0wyo6860/ls_dcp.mp3",
    "Лучший": "https://dl.dropbox.com/s/h803yjfxmyla8xc/luchshii.mp3",
    "Мать сдохла": "https://dl.dropbox.com/s/p8ef0q8s3a5xd9y/mat_sdohla.mp3",
    "Мать твоя": "https://dl.dropbox.com/s/pi6pejx07x1f96v/mat_tvoia.wav.mp3",
    "М-м-монстер килл": "https://dl.dropbox.com/s/5fshdkpqqsvz462/mmmonsterkill.mp3",
    "М Н О Г О Х О Д О В О Ч К А": "https://dl.dropbox.com/s/lacrik6yhl5r9dd/mnogohodovochka.mp3",
    "Мусор": "https://dl.dropbox.com/s/xash4c4whzl4qhr/musor.mp3",
    "Мусор тварь": "https://dl.dropbox.com/s/ga5ijxm03swfbn0/musortvar.wav.mp3",
    "НЫЫЫЫАААААА": "https://dl.dropbox.com/s/5gyed5u3hxpcidd/naaa.wav.mp3",
    "Нету помощи": "https://dl.dropbox.com/s/bv734tvnyghrze0/netu_pomoshi.wav.mp3",
    "НААААА": "https://dl.dropbox.com/s/agz1ekluujiogr8/nyaaaaa.mp30",
    "О боже": "https://dl.dropbox.com/s/jw7egg6c2upgbtc/o_boje.wav.mp3",
    "Пидарасы": "https://dl.dropbox.com/s/v5wlxw2n56eyam2/pidarasi.wav.mp3",
    "Поешь": "https://dl.dropbox.com/s/ay0al8l5h2jeei5/poesh.mp3",
    "Помойка": "https://dl.dropbox.com/s/csp8h7sar1a5flw/pomoyka.mp3",
    "Попал": "https://dl.dropbox.com/s/qof7ve18wx7re1y/popal.mp3",
    "Пошел нахуй": "https://dl.dropbox.com/s/0vgoad0foqa95zt/poshel_nahui.wav.mp3",
    "Сейчас я вас буду резать": "https://dl.dropbox.com/s/wdm7qgcmhywxow3/rezat.mp3",
    "ВИ КА А А": "https://dl.dropbox.com/s/evx47n68lxb3bjv/ruchit.wav.mp3",
    "Сдохни ААА": "https://dl.dropbox.com/s/cjvtkegjpnt75eb/sdohni_naa.mp3",
    "Шоо?": "https://dl.dropbox.com/s/xrb1od466rah7kg/sho.mp3",
    "СЫН ДЕРЬМА НЫЫА": "https://dl.dropbox.com/s/apu1ovaourlbpfk/sin_derma.mp3",
    "СЫН ДЕРЬМА ВИ КА": "https://dl.dropbox.com/s/altsabw9gkuktaj/sinder.mp3",
    "ААА СЛОЖНА ААА СЛОЖНА": "https://dl.dropbox.com/s/wshy5ua9sgv0vr7/slozno.mp3",
    "Проиграл в голосину": "https://dl.dropbox.com/s/uiam17lvdcx24u6/smeetsa.mp3",
    "Стан": "https://dl.dropbox.com/s/l2dydgwgygvec0w/stun.mp3",
    "ТЫ УМРЕШЬ ТВАРЫНА": "https://dl.dropbox.com/s/b9yuvifdl94jzho/umresh.wav.mp3",
    "VI KA": "https://dl.dropbox.com/s/h3kh7jnb16t7jdz/vi_ka.mp3",
    "НА ВЫХОД": "https://dl.dropbox.com/s/8s7h142v025xuq4/vihod.wav.mp3",
    "Всола": "https://dl.dropbox.com/s/0fdnmce7gi9n1ue/vsola.wav.mp3",
    "Всоляного": "https://dl.dropbox.com/s/phhw3os5zqaqywe/vsolyanogo.mp3",
    "Запилил уебка": "https://dl.dropbox.com/s/k5o9w1wzcloq5qy/zapilil.mp3",
    "Здарова, тварына": "https://dl.dropbox.com/s/og7w8150zk3rjny/zdarova_tvarina.mp3",
    "Андрюха": "https://dl.dropbox.com/s/35y227etx07qz8l/papich-andryuha.mp3",
    "Что с ебалом": "https://dl.dropbox.com/s/csa1ihq1rphqoki/papich-chto-s-ebalom.mp3",
    "Фурион": "https://dl.dropbox.com/s/m5qlogcszgrbr38/papich-furion.mp3",
    "КАЙФ": "https://dl.dropbox.com/s/cm989amthxqmd5g/papich-kayf.mp3",
    "На недельку...": "https://dl.dropbox.com/s/e3eig0ta7z40nwh/papich-na-nedel-ku.mp3",
    "Ненавижу доту": "https://dl.dropbox.com/s/hd5skmf0bfqmvy9/papich-nenavizhu-dotu.mp3",
    "ШОК контент": "https://dl.dropbox.com/s/d2n5zdtpz8uxn9m/papich-shok-kontent.mp3",
    "гыхгыгыхыыыы": "https://dl.dropbox.com/s/xbhdosm0uvu9d3b/papich-gyhgygyhyyyy.mp30",
    "Подрубил проверяйте": "https://dl.dropbox.com/s/qoaswbit6cohpyd/papich-podrubil-proveryayte.mp3",
    "Вынес мусор": "https://dl.dropbox.com/s/2lpofqmzdlmy0da/papich-vynes-musor.mp3",
    "Что ты несешь": "https://dl.dropbox.com/s/bs240qaj47xega8/papich-chto-ty-nesesh.mp3",
};